# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae7385af5b6a9fd0837eb42606ebcb50cda61ba95946fafd2fced1d2ccac3bd5564c07e80dc1bf6962b4db45e2baa2db4ee34bcae9cd15fb9aac6afdec7925c6

test:
  secret_key_base: d6b58e6b939913d47640b1172c3acbbb0123714af674191522aaf4ea7058ec3b76f2bdb82a053ffb04b93fcdf24bee6aa7eaa286aaef3d823682958de4f18d87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
